libraries:
  Movies:
    operations:
      delete_unmanaged_collections: true
    metadata_path:
    - git: PMM/award/choice
      schedule: weekly(wednesday)
    - git: PMM/award/golden
      schedule: weekly(wednesday)
    - git: PMM/award/oscars
      schedule: weekly(wednesday)
      template_variables:
        radarr_tag: PMM,PMM-<<collection_name>> # New
        item_radarr_tag: PMM,PMM-<<collection_name>> # Existing
    - git: PMM/award/other
      schedule: weekly(wednesday)
    - git: PMM/award/spirit
      schedule: weekly(wednesday)
    - git: PMM/award/sundance
      schedule: weekly(wednesday)
    - git: PMM/chart/basic
      schedule: weekly(monday)
    - git: PMM/chart/imdb
      schedule: weekly(monday)
      template_variables:
        radarr_tag: PMM,PMM-<<collection_name>> # New
        item_radarr_tag: PMM,PMM-<<collection_name>> # Existing
    - git: PMM/chart/other
      schedule: weekly(monday)
    - git: PMM/chart/tautulli
      schedule: weekly(monday)
    - git: PMM/chart/tmdb
      schedule: weekly(monday)
    - git: PMM/chart/trakt
      schedule: weekly(monday)
    - git: PMM/actor
      schedule: weekly(tuesday)
    - git: PMM/genre
      schedule: weekly(tuesday)
    - git: PMM/movie/decade
    - git: PMM/movie/director
      schedule: weekly(tuesday)
    - git: PMM/movie/franchise
    - git: PMM/movie/universe
      template_variables:
        radarr_tag: PMM,PMM-<<collection_name>> # New
        item_radarr_tag: PMM,PMM-<<collection_name>> # Existing
    - git: PMM/movie/seasonal
      template_variables:
        radarr_tag: PMM,PMM-<<collection_name>> # New
        item_radarr_tag: PMM,PMM-<<collection_name>> # Existing
    - git: PMM/movie/streaming
    overlay_path:
    - remove_overlays: false
    - git: PMM/overlays/audio_codec
    - git: PMM/overlays/audio_language
    - git: PMM/overlays/direct_play
    - git: PMM/overlays/imdb_top_250
    - git: PMM/overlays/ratings
    - git: PMM/overlays/resolution
    - git: PMM/overlays/special_release
    - git: PMM/overlays/streaming
    - git: PMM/overlays/video_format
  TV Shows:
    operations:
      delete_unmanaged_collections: true
    metadata_path:
    - git: PMM/award/choice
      schedule: monthly(1)
    - git: PMM/award/golden
      schedule: monthly(1)
    - git: PMM/award/emmy
      schedule: monthly(1)
    - git: PMM/chart/basic
      schedule: weekly(monday)
    - git: PMM/chart/imdb
      schedule: weekly(monday)
    - git: PMM/chart/other
      schedule: weekly(monday)
    - git: PMM/chart/tautulli
      schedule: weekly(monday)
    - git: PMM/chart/tmdb
      schedule: weekly(monday)
    - git: PMM/chart/trakt
      schedule: weekly(monday)
    - git: PMM/genre
    - git: PMM/show/decade
    - git: PMM/show/network
    - git: PMM/show/streaming
    overlay_path:
    - remove_overlays: false
    - git: PMM/overlays/audio_codec
    - git: PMM/overlays/audio_codec
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/audio_codec
      template_variables:
        overlay_level: season
    - git: PMM/overlays/audio_language
    - git: PMM/overlays/audio_language
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/audio_language
      template_variables:
        overlay_level: season
    - git: PMM/overlays/direct_play
    - git: PMM/overlays/direct_play
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/direct_play
      template_variables:
        overlay_level: season
    - git: PMM/overlays/ratings
    - git: PMM/overlays/ratings
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/ratings
      template_variables:
        overlay_level: season
    - git: PMM/overlays/resolution
    - git: PMM/overlays/resolution
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/resolution
      template_variables:
        overlay_level: season
    - git: PMM/overlays/special_release
    - git: PMM/overlays/special_release
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/special_release
      template_variables:
        overlay_level: season
    - git: PMM/overlays/streaming
    - git: PMM/overlays/streaming
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/streaming
      template_variables:
        overlay_level: season
    - git: PMM/overlays/video_format
    - git: PMM/overlays/video_format
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - git: PMM/overlays/video_format
      template_variables:
        overlay_level: season
playlist_files:
- git: PMM/playlist
settings: # Can be individually specified per library as well
  asset_depth: 1
  asset_directory: /data/media/.config/Plex-Meta-Manager/assets
  asset_folders: true
  cache_builders: true
  cache_expiration: 14
  cache: true
  create_asset_folders: false
  custom_repo: https://raw.githubusercontent.com/bakerboy448/pmm-config/main/
  delete_below_minimum: true
  delete_not_scheduled: false
  dimensional_asset_rename: true
  download_url_assets: true
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 2
  minimum_items: 2
  missing_only_released: true
  only_filter_missing: false
  playlist_sync_to_users: all
  run_again_delay: 2
  save_missing: true
  show_asset_not_needed: false
  show_filtered: true
  show_missing_assets: false
  show_missing_episode_assets: false
  show_missing_season_assets: false
  show_missing: true
  show_options: true
  show_unmanaged: true
  sync_mode: sync
  tvdb_language: eng
  verify_ssl: true
  default_collection_order:
  check_nightly: true
  playlist_report: true
  prioritize_assets: false
  save_report: true
webhooks:
  error: notifiarr
  run_end: notifiarr
  run_start: notifiarr
  changes: notifiarr
  version: notifiarr
plex: # Can be individually specified per library as well; REQUIRED for the script to run
  clean_bundles: false
  empty_trash: false
  optimize: false
  timeout: 120
  token: (removed)
  url: http://localhost:32400
tmdb: # REQUIRED for the script to run
  apikey: (removed)
  language: en
  cache_expiration: 45
  region:
tautulli: # Can be individually specified per library as well
  apikey: (removed)
  url: http://localhost:8181/tautulli
notifiarr:
  apikey: (removed)
radarr: # Can be individually specified per library as well
  add_existing: true
  availability: released
  monitor: true
  plex_path:
  quality_profile: HD - No Remux
  radarr_path:
  root_folder_path: /data/media/media/movies
  search: false
  tag: pmm
  token: (removed)
  url: http://localhost:7878/radarr
  add_missing: false
  upgrade_existing: false
sonarr: # Can be individually specified per library as well
  add_existing: true
  cutoff_search: false
  language_profile: English
  monitor: all
  plex_path:
  quality_profile: HD - Low - No Upgrade
  root_folder_path: /data/media/media/tv
  search: true
  season_folder: true
  series_type: standard
  sonarr_path:
  tag: pmm
  token: (removed)
  url: http://localhost:8989/sonarr
  add_missing: false
  upgrade_existing: false
trakt:
  client_id: (removed)
  client_secret: (removed)
  authorization:
    access_token: (removed)
    token_type: Bearer
    expires_in: 7889237
    refresh_token: (removed)
    scope: public
    created_at: 1649919626
  pin:
