libraries:
  Movies:
    operations:
      delete_collections:
        managed: false # Keep only PMM Managed
        configured: false # Keep only collections in this run
    metadata_path:
    - pmm: award/choice
      schedule: weekly(wednesday)
    - pmm: golden
      schedule: weekly(wednesday)
    - pmm: oscars
      schedule: weekly(wednesday)
      template_variables:
        radarr_monitor: false
        radarr_tag: PMM,PMM-<<collection_name>>   # New
        item_radarr_tag: PMM,PMM-<<collection_name>>   # Existing
        radarr_add_missing: true
    - pmm: award/spirit
      schedule: weekly(wednesday)
    - pmm: award/sundance
      schedule: weekly(wednesday)
    - pmm: chart/basic
      schedule: weekly(monday)
    - pmm: chart/imdb
      schedule: weekly(monday)
      template_variables:
        use_lowest: false
        radarr_add_missing_popular: false
        radarr_monitor_popular: false
        radarr_add_missing_top: true
        radarr_monitor_top: false
        radarr_tag: PMM,PMM-<<collection_name>>   # New
        item_radarr_tag: PMM,PMM-<<collection_name>>   # Existing
    - pmm: chart/tautulli
      schedule: weekly(monday)
    - pmm: chart/tmdb
    - pmm: chart/trakt
      schedule: weekly(monday)
    - pmm: actor
      schedule: weekly(tuesday)
      template_variables:
         # Sets the style of posters: bw or rainier
        style: rainier
    - pmm: genre
      schedule: weekly(tuesday)
    - pmm: decade
    - pmm: movie/director
      schedule: weekly(tuesday)
      template_variables:
         # Sets the style of posters: bw or rainier
        style: rainier
    - pmm: movie/franchise
      template_variables:
        radarr_tag: PMM,PMM-<<collection_name>>   # New
        item_radarr_tag: PMM,PMM-<<collection_name>>   # Existing
    - pmm: movie/universe
      template_variables:
        radarr_tag: PMM,PMM-<<collection_name>>   # New
        item_radarr_tag: PMM,PMM-<<collection_name>>   # Existing
    - pmm: movie/seasonal
      template_variables:
        radarr_monitor: false
        radarr_add_missing: true
        radarr_tag: PMM,PMM-<<collection_name>>   # New
        item_radarr_tag: PMM,PMM-<<collection_name>>   # Existing
    - pmm: streaming
    overlay_path:
    - remove_overlays: false
    - reapply_overlay: false
    - pmm: ribbon
    - pmm: mediastinger
    - pmm: audio_codec
    - pmm: direct_play
    - pmm: ratings
    - pmm: resolution
    - pmm: streaming
    - pmm: video_format
  TV Shows:
    operations:
      delete_collections:
        managed: false
        unconfigured: false
    metadata_path:
    - pmm: award/choice
      schedule: monthly(1)
    - pmm: award/golden
      schedule: monthly(1)
      # template_variables:
        # sonarr_tag: PMM,PMM-<<collection_name>>   # New
        # item_sonarr_tag: PMM,PMM-<<collection_name>>   # Existing
    - pmm: award/emmy
      schedule: monthly(1)
      # template_variables:
        # sonarr_tag: PMM,PMM-<<collection_name>>   # New
        # item_sonarr_tag: PMM,PMM-<<collection_name>>   # Existing
    - pmm: chart/basic
      schedule: weekly(monday)
    - pmm: chart/imdb
      schedule: weekly(monday)
      template_variables:
        use_lowest: false
    - pmm: chart/tautulli
      schedule: weekly(monday)
    - pmm: chart/tmdb
    - pmm: chart/trakt
      schedule: weekly(monday)
    - pmm: genre
    - pmm: decade
    - pmm: show/network
    - pmm: streaming
    - pmm: show/franchise
      # template_variables:
        # sonarr_add_missing: false
        # sonarr_monitor: false
        # sonarr_tag: PMM,PMM-<<collection_name>>   # New
        # item_sonarr_tag: PMM,PMM-<<collection_name>>   # Existing
    overlay_path:
    - schedule:
     - monthly(1)
     - monthly(15)
    - remove_overlays: false
    - reapply_overlay: false
    - pmm: audio_codec
    - pmm: audio_codec
      template_variables:
        overlay_level: episode
    - pmm: audio_codec
      template_variables:
        overlay_level: season
    - pmm: direct_play
    - pmm: direct_play
      template_variables:
        overlay_level: episode
    - pmm: direct_play
      template_variables:
        overlay_level: season
    - pmm: ratings
    - pmm: ratings
      template_variables:
        overlay_level: episode
    - pmm: ratings
      template_variables:
        overlay_level: season
    - pmm: resolution
    - pmm: resolution
      template_variables:
        overlay_level: episode
    - pmm: resolution
      template_variables:
        overlay_level: season
    - pmm: streaming
    - pmm: streaming
      template_variables:
        overlay_level: episode
    - pmm: streaming
      template_variables:
        overlay_level: season
    - pmm: video_format
    - pmm: video_format
      template_variables:
        overlay_level: episode
    - pmm: video_format
      template_variables:
        overlay_level: season
playlist_files:
- pmm: playlist
settings: # Can be individually specified per library as well
  asset_depth: 1
  asset_directory: /data/media/.config/Plex-Meta-Manager/assets
  asset_folders: true
  cache_builders: true
  cache_expiration: 30
  cache: true
  create_asset_folders: false
  custom_repo: https://raw.githubusercontent.com/bakerboy448/pmm-config/main/
  delete_below_minimum: true
  delete_not_scheduled: false
  dimensional_asset_rename: true
  download_url_assets: true
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 2
  minimum_items: 2
  missing_only_released: true
  only_filter_missing: false
  playlist_sync_to_users: all
  run_again_delay: 2
  show_asset_not_needed: false
  show_filtered: true
  show_missing_assets: false
  show_missing_episode_assets: false
  show_missing_season_assets: false
  show_missing: false
  show_options: true
  show_unmanaged: true
  sync_mode: sync
  tvdb_language: eng
  verify_ssl: true
  default_collection_order:
  check_nightly: true
  playlist_report: true
  prioritize_assets: false
  save_report: true
  show_unconfigured: true
webhooks:
  error: notifiarr
  run_end: notifiarr
  run_start: notifiarr
  changes: notifiarr
  version: notifiarr
plex: # Can be individually specified per library as well; REQUIRED for the script to run
  clean_bundles: false
  empty_trash: false
  optimize: false
  timeout: 120
  token: (removed)
  url: http://localhost:32400
tmdb: # REQUIRED for the script to run
  apikey: (removed)
  language: en
  cache_expiration: 45
  region:
tautulli: # Can be individually specified per library as well
  apikey: (removed)
  url: http://localhost:8181/tautulli
notifiarr:
  apikey: (removed)
radarr: # Can be individually specified per library as well
  add_existing: true
  availability: released
  monitor: true
  plex_path:
  quality_profile: HD - No Remux
  radarr_path:
  root_folder_path: /data/media/media/movies
  search: false
  tag: pmm
  token: (removed)
  url: http://localhost:7878/radarr
  add_missing: false
  upgrade_existing: false
# sonarr: # Can be individually specified per library as well
#  add_existing: true
#  cutoff_search: false
#  language_profile: English
#  monitor: all
#  plex_path:
#  quality_profile: HD - Low - No Upgrade
#  root_folder_path: /data/media/media/tv
#  search: true
#  season_folder: true
#  series_type: standard
  # sonarr_path:
#  tag: pmm
#  token: (removed)
#  url: http://localhost:8989/# sonarr
#  add_missing: false
#  upgrade_existing: false
trakt:
  client_id: (removed)
  client_secret: (removed)
  authorization:
    access_token: (removed)
    token_type: Bearer
    expires_in: 7889237
    refresh_token: (removed)
    scope: public
    created_at: 1665832520
  pin:
