libraries: # Library mappings must have a colon (:) placed after them
  Movies:
    missing_path: /data/media/.config/Plex-Meta-Manager/Missing/Movies.yml
    overlay_path:
      - repo: video-overlays
      - remove_overlays: true
    metadata_path:
      - repo: movies-special
      - repo: movies-best
      - repo: movies-collections
      - repo: movies-general
      - repo: movies-holidays
      - repo: movies-mcu
    operations:
      assets_for_all: true
      delete_unmanaged_collections: true
  TV Shows:
    missing_path: /data/media/.config/Plex-Meta-Manager/Missing/TV.yml
    metadata_path:
      - repo: tv
      - repo: tv-meta
      - repo: tv-networks
      - repo: networks
  TV Shows - Cartoons:
    missing_path: /data/media/.config/Plex-Meta-Manager/Missing/TV-Cartoons.yml
    metadata_path:
      - repo: tv
      - repo: tv-meta
  TV Shows - Cartoons Kids:
    missing_path: /data/media/.config/Plex-Meta-Manager/Missing/TV-Cartoons-Kids.yml
    metadata_path:
      - repo: tv
      - repo: tv-meta
settings: # Can be individually specified per library as well
  asset_depth: 1
  asset_directory: /data/media/.config/Plex-Meta-Manager/assets
  asset_folders: true
  cache_builders: true
  cache_expiration: 14
  cache: true
  create_asset_folders: false
  custom_repo: https://raw.githubusercontent.com/bakerboy448/pmm-config/main/
  delete_below_minimum: true
  delete_not_scheduled: false
  dimensional_asset_rename: true
  download_url_assets: true
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 2
  minimum_items: 2
  missing_only_released: true
  only_filter_missing: false
  playlist_sync_to_users: all
  run_again_delay: 2
  save_missing: true
  show_asset_not_needed: false
  show_filtered: true
  show_missing_assets: false
  show_missing_episode_assets: false
  show_missing_season_assets: false
  show_missing: true
  show_options: true
  show_unmanaged: true
  sync_mode: sync
  tvdb_language: eng
  verify_ssl: true
  default_collection_order:
  check_nightly: true
webhooks:
  error: notifiarr
  run_end: notifiarr
  run_start: notifiarr
  changes: notifiarr
  version: notifiarr
plex: # Can be individually specified per library as well; REQUIRED for the script to run
  clean_bundles: false
  empty_trash: false
  optimize: false
  timeout: 120
  token: (removed)
  url: http://localhost:32400
tmdb: # REQUIRED for the script to run
  apikey: (removed)
  language: en
  cache_expiration: 45
  region:
tautulli: # Can be individually specified per library as well
  apikey: (removed)
  url: http://localhost:8181/tautulli
notifiarr:
  apikey: (removed)
radarr: # Can be individually specified per library as well
  add_existing: true
  availability: released
  monitor: true
  plex_path:
  quality_profile: HD - No Remux
  radarr_path:
  root_folder_path: /data/media/media/movies
  search: false
  tag: pmm
  token: (removed)
  url: http://localhost:7878/radarr
  add_missing: true
  upgrade_existing: false
sonarr: # Can be individually specified per library as well
  add_existing: true
  cutoff_search: false
  language_profile: English
  monitor: all
  plex_path:
  quality_profile: HD - Low - No Upgrade
  root_folder_path: /data/media/media/tv
  search: true
  season_folder: true
  series_type: standard
  sonarr_path:
  tag: pmm
  token: (removed)
  url: http://localhost:8989/sonarr
  add_missing: true
  upgrade_existing: false
trakt:
  client_id: (removed)
  client_secret: (removed)
  authorization:
    access_token: (removed)
    token_type: Bearer
    expires_in: 7889237
    refresh_token: (removed)
    scope: public
    created_at: 1649919626
  pin:
