libraries:
  Movies:
    operations:
      delete_collections:
        unmanaged: true
    metadata_path:
    - pmm: award/choice
      schedule: weekly(wednesday)
    - pmm: award/golden
      schedule: weekly(wednesday)
    - pmm: award/oscars
      schedule: weekly(wednesday)
      template_variables:
        radarr_monitor: false
        radarr_tag: PMM,PMM-<<collection_name>>   # New
        item_radarr_tag: PMM,PMM-<<collection_name>>   # Existing
        radarr_add_missing: true
    - pmm: award/spirit
      schedule: weekly(wednesday)
    - pmm: award/sundance
      schedule: weekly(wednesday)
    - pmm: chart/basic
      schedule: weekly(monday)
    - pmm: chart/imdb
      schedule: weekly(monday)
      template_variables:
        use_lowest: false
        radarr_add_missing_popular: false
        radarr_monitor_popular: false
        radarr_add_missing_top: true
        radarr_monitor_top: false
        radarr_tag: PMM,PMM-<<collection_name>>   # New
        item_radarr_tag: PMM,PMM-<<collection_name>>   # Existing
    - pmm: chart/tautulli
      schedule: weekly(monday)
    - pmm: chart/tmdb
    - pmm: chart/trakt
      schedule: weekly(monday)
    - pmm: actor
      schedule: weekly(tuesday)
      template_variables:
         # Sets the style of posters: bw or rainier
        style: rainier
    - pmm: genre
      schedule: weekly(tuesday)
    - pmm: movie/decade
    - pmm: movie/director
      schedule: weekly(tuesday)
      template_variables:
         # Sets the style of posters: bw or rainier
        style: rainier
    - pmm: movie/franchise
      template_variables:
        radarr_tag: PMM,PMM-<<collection_name>>   # New
        item_radarr_tag: PMM,PMM-<<collection_name>>   # Existing
    - pmm: movie/universe
      template_variables:
        radarr_tag: PMM,PMM-<<collection_name>>   # New
        item_radarr_tag: PMM,PMM-<<collection_name>>   # Existing
    - pmm: movie/seasonal
      template_variables:
        radarr_monitor: false
        radarr_add_missing: true
        radarr_tag: PMM,PMM-<<collection_name>>   # New
        item_radarr_tag: PMM,PMM-<<collection_name>>   # Existing
    - pmm: streaming
    overlay_path:
    - remove_overlays: false
    - pmm: ribbon
    - pmm: overlays/audio_codec
    - pmm: overlays/direct_play
    - pmm: overlays/ratings
    - pmm: overlays/resolution
    - pmm: overlays/streaming
    - pmm: overlays/video_format
  TV Shows:
    operations:
      delete_collections:
        unmanaged: true
    metadata_path:
    - pmm: award/choice
      schedule: monthly(1)
    - pmm: award/golden
      schedule: monthly(1)
      template_variables:
        # sonarr_tag: PMM,PMM-<<collection_name>>   # New
 #       item_# sonarr_tag: PMM,PMM-<<collection_name>>   # Existing
    - pmm: award/emmy
      schedule: monthly(1)
      template_variables:
        # sonarr_tag: PMM,PMM-<<collection_name>>   # New
 #       item_# sonarr_tag: PMM,PMM-<<collection_name>>   # Existing
    - pmm: chart/basic
      schedule: weekly(monday)
    - pmm: chart/imdb
      schedule: weekly(monday)
      template_variables:
        use_lowest: false
    - pmm: chart/tautulli
      schedule: weekly(monday)
    - pmm: chart/tmdb
    - pmm: chart/trakt
      schedule: weekly(monday)
    - pmm: genre
    - pmm: show/decade
    - pmm: show/network
    - pmm: streaming
    - pmm: show/franchise
      schedule: monthly(1)
#      template_variables:
        # sonarr_add_missing: false
        # sonarr_monitor: false
        # sonarr_tag: PMM,PMM-<<collection_name>>   # New
 #       item_# sonarr_tag: PMM,PMM-<<collection_name>>   # Existing
    overlay_path:
    - remove_overlays: false
    - pmm: overlays/audio_codec
    - pmm: overlays/audio_codec
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - pmm: overlays/audio_codec
      template_variables:
        overlay_level: season
    - pmm: overlays/direct_play
    - pmm: overlays/direct_play
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - pmm: overlays/direct_play
      template_variables:
        overlay_level: season
    - pmm: overlays/ratings
    - pmm: overlays/ratings
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - pmm: overlays/ratings
      template_variables:
        overlay_level: season
    - pmm: overlays/resolution
    - pmm: overlays/resolution
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - pmm: overlays/resolution
      template_variables:
        overlay_level: season
    - pmm: overlays/streaming
    - pmm: overlays/streaming
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - pmm: overlays/streaming
      template_variables:
        overlay_level: season
    - pmm: overlays/video_format
    - pmm: overlays/video_format
      schedule: monthly(28)
      template_variables:
        overlay_level: episode
    - pmm: overlays/video_format
      template_variables:
        overlay_level: season
playlist_files:
- pmm: playlist
settings: # Can be individually specified per library as well
  asset_depth: 1
  asset_directory: /data/media/.config/Plex-Meta-Manager/assets
  asset_folders: true
  cache_builders: true
  cache_expiration: 14
  cache: true
  create_asset_folders: false
  custom_repo: https://raw.githubusercontent.com/bakerboy448/pmm-config/main/
  delete_below_minimum: true
  delete_not_scheduled: false
  dimensional_asset_rename: true
  download_url_assets: true
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 2
  minimum_items: 2
  missing_only_released: true
  only_filter_missing: false
  playlist_sync_to_users: all
  run_again_delay: 2
  save_missing: true
  show_asset_not_needed: false
  show_filtered: true
  show_missing_assets: false
  show_missing_episode_assets: false
  show_missing_season_assets: false
  show_missing: true
  show_options: true
  show_unmanaged: true
  sync_mode: sync
  tvdb_language: eng
  verify_ssl: true
  default_collection_order:
  check_nightly: false
  playlist_report: true
  prioritize_assets: false
  save_report: true
  show_unconfigured: true
webhooks:
  error: (redacted)
  run_end: (redacted)
  run_start: (redacted)
  changes: (redacted)
  version: (redacted)
plex: # Can be individually specified per library as well; REQUIRED for the script to run
  clean_bundles: false
  empty_trash: false
  optimize: false
  timeout: 120
  token: (redacted)
  url: (redacted)
tmdb: # REQUIRED for the script to run
  apikey: (redacted)
  language: en
  cache_expiration: 45
  region:
tautulli: # Can be individually specified per library as well
  apikey: (redacted)
  url: (redacted)
notifiarr:
  apikey: (redacted)
radarr: # Can be individually specified per library as well
  add_existing: true
  availability: released
  monitor: true
  plex_path:
  quality_profile: HD - No Remux
  radarr_path:
  root_folder_path: /data/media/media/movies
  search: false
  tag: pmm
  token: (redacted)
  url: (redacted)
  add_missing: false
  upgrade_existing: false
# sonarr: # Can be individually specified per library as well
#  add_existing: true
#  cutoff_search: false
#  language_profile: English
#  monitor: all
#  plex_path:
#  quality_profile: HD - Low - No Upgrade
#  root_folder_path: /data/media/media/tv
#  search: true
#  season_folder: true
#  series_type: standard
  # sonarr_path:
#  tag: pmm
#  token: (redacted)
#  url: (redacted)
#  add_missing: false
#  upgrade_existing: false
trakt:
  client_id: (redacted)
  client_secret: (redacted)
  authorization:
    access_token: (redacted)
    token_type: Bearer
    expires_in: 7889237
    refresh_token: (redacted)
    scope: public
    created_at: 1665832520
  pin:
