libraries: # Library mappings must have a colon (:) placed after them
  Movies:
    metadata_path:
      - repo: movies-special.yml
      - repo: movies-best.yml
      - repo: movies-collections.yml
      - repo: movies-general.yml
      - repo: movies-holidays.yml
      - repo: movies-mcu.yml
      - repo: video-overlays.yml
    operations:
      delete_collections_with_less: 2
      delete_unmanaged_collections: true
    radarr: # Can be individually specified per library as well
      add_existing: true
      availability: released
      monitor: true
      plex_path:
      quality_profile: HD - No Remux
      radarr_path:
      root_folder_path: /data/media/media/movies
      search: false
      tag: pmm
      token: (removed)
      url: http://localhost:7878/radarr
      add_missing: true
  TV Shows:
    metadata_path:
      - repo: tv.yml
      - repo: tv-meta.yml
      - repo: tv-networks.yml
      - repo: video-overlays.yml
    operations:
      delete_collections_with_less: 2
    sonarr: # Can be individually specified per library as well
      add_existing: true
      cutoff_search: false
      language_profile: English
      monitor: all
      plex_path:
      quality_profile: HD - Low - No Upgrade
      root_folder_path: /data/media/media/tv
      search: true
      season_folder: true
      series_type: standard
      sonarr_path:
      tag: pmm
      token: (removed)
      url: http://localhost:8989/sonarr
      add_missing: true
  TV Shows - Cartoons:
    metadata_path:
      - repo: tv.yml
      - repo: tv-meta.yml
    operations:
      delete_collections_with_less: 2
  TV Shows - Cartoons Kids:
    metadata_path:
      - repo: tv.yml
      - repo: tv-meta.yml
    operations:
      delete_collections_with_less: 2
settings: # Can be individually specified per library as well
  asset_directory:
    - config/assets
  asset_folders: true
  asset_depth: 1
  dimensional_asset_rename: true
  cache_expiration: 30
  cache: true
  create_asset_folders: false
  delete_below_minimum: true
  delete_not_scheduled: false
  dimensional_asset_rename: false
  ignore_ids:
  ignore_imdb_ids:
  missing_only_released: true
  only_filter_missing: false
  run_again_delay: 2
  save_missing: false
  show_filtered: false
  show_missing_assets: false
  show_missing_season_assets: false
  show_missing: true
  show_options: true
  show_unmanaged: true
  sync_mode: sync
  tvdb_language: eng
  minimum_items: 2
  default_collection_order:
  playlist_sync_to_users: all
  download_url_assets: true
  item_refresh_delay: 0
  verify_ssl: true
  show_missing_episode_assets: false
  show_asset_not_needed: true
  custom_repo: https://raw.githubusercontent.com/bakerboy448/plex-meta-manger/main/
webhooks:
  error: notifiarr
  run_end: notifiarr
  run_start: notifiarr
  changes:
    - notifiarr
plex: # Can be individually specified per library as well; REQUIRED for the script to run
  clean_bundles: false
  empty_trash: false
  optimize: false
  timeout: 120
  token: (removed)
  url: http://localhost:32400
tmdb: # REQUIRED for the script to run
  apikey: (removed)
  language: en
tautulli: # Can be individually specified per library as well
  apikey: (removed)
  url: http://localhost:8181/tautulli
notifiarr:
  apikey: (removed)
trakt:
  client_id: (removed)
  client_secret: (removed)
  authorization:
    access_token: (removed)
    created_at: 1639938124
    expires_in: 7889237
    refresh_token: (removed)
    scope: public
    token_type: Bearer
