libraries: # Library mappings must have a colon (:) placed after them
  Movies:
    metadata_path:
      - url: https://raw.githubusercontent.com/bakerboy448/plex-meta-manger/main/movies-best.yml
      - url: https://raw.githubusercontent.com/bakerboy448/plex-meta-manger/main/movies-collections.yml
      - url: https://raw.githubusercontent.com/bakerboy448/plex-meta-manger/main/movies-general.yml
      - url: https://raw.githubusercontent.com/bakerboy448/plex-meta-manger/main/movies-holidays.yml
      - url: https://raw.githubusercontent.com/bakerboy448/plex-meta-manger/main/movies-mcu.yml
    operations:
      delete_unmanaged_collections: true
      delete_collections_with_less: 2
    radarr: # Can be individually specified per library as well
      url: http://localhost:7878/radarr
      token: (removed)
      add: true
      add_existing: true
      root_folder_path: /data/media/media/movies
      monitor: true
      availability: released
      quality_profile: HD - No Remux
      tag: pmm
      search: true
      radarr_path:
      plex_path:
  TV Shows:
    metadata_path:
      - url: https://raw.githubusercontent.com/bakerboy448/plex-meta-manger/main/tv.yml
      - url: https://raw.githubusercontent.com/bakerboy448/plex-meta-manger/main/tv-meta.yml
    operations:
      delete_unmanaged_collections: true
      delete_collections_with_less: 2
    sonarr: # Can be individually specified per library as well
      url: http://localhost:8989/sonarr
      token: (removed)
      add: true
      add_existing: true
      root_folder_path: /data/media/media/tv
      monitor: all
      quality_profile: HD - Low - No Upgrade
      language_profile: English
      series_type: standard
      season_folder: true
      tag: pmm
      search: true
      cutoff_search: false
      sonarr_path:
      plex_path:
  TV Shows - Cartoons:
    metadata_path:
      - url: https://raw.githubusercontent.com/bakerboy448/plex-meta-manger/main/tv.yml
      - url: https://raw.githubusercontent.com/bakerboy448/plex-meta-manger/main/tv-meta.yml
    operations:
      delete_unmanaged_collections: true
      delete_collections_with_less: 2
  TV Shows - Cartoons Kids:
    metadata_path:
      - url: https://raw.githubusercontent.com/bakerboy448/plex-meta-manger/main/tv.yml
      - url: https://raw.githubusercontent.com/bakerboy448/plex-meta-manger/main/tv-meta.yml
    operations:
      delete_unmanaged_collections: true
      delete_collections_with_less: 2
settings: # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  create_asset_folders: true
  sync_mode: sync
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  show_missing_assets: true
  save_missing: true
  run_again_delay: 2
  missing_only_released: true
  only_filter_missing: false
  collection_minimum: 2
  delete_below_minimum: true
  delete_not_scheduled: false
  tvdb_language: eng
  asset_depth: 0
  show_missing_season_assets: false
  show_options: false
  ignore_ids:
  ignore_imdb_ids:
webhooks:
  error: notifiarr
  run_start: notifiarr
  run_end: notifiarr
  collection_changes:
    - notifiarr
plex: # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://localhost:32400
  token: (removed)
  timeout: 120
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb: # REQUIRED for the script to run
  apikey: (removed)
  language: en
tautulli: # Can be individually specified per library as well
  url: http://localhost:8181/tautulli
  apikey: (removed)
notifiarr:
  apikey: (removed)
trakt:
  client_id: (removed)
  client_secret: (removed)
  authorization:
    access_token: (removed)
    token_type: Bearer
    expires_in: 7889237
    refresh_token: (removed)
    scope: public
    created_at: 1639938124
